name: Backend CI/CD with Maven

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Install dependencies and run tests
        working-directory: ./backend
        run: mvn --batch-mode --update-snapshots clean install